### ISSUE TITLE
Contributing guidelines

### ISSUE THREAD

**Issue by pathumego** [akuru/sinhala-unicode-guide#7]
I think if we write some simple contributing guidelines would be easy for people to write  
@bhagyas is index.adoc built from `src`? I am not clear which file should we work with?

**Comment by bhagyas** [comment]
You can modify the `src/asciidoc/content.adoc` file which is based on the original odt file I found on the extras folder. I wasn't sure if the index.adoc is the same as content.adoc, so both were converted.

 I formatted the content on `src/asciidoc/content.adoc`, so maybe `index.adoc` can be removed.

For some tips on asciidoc formatting for GitHub: https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74

**Comment by pathumego** [comment]
Thanks! The contents in the index.adoc is the latest. I made updates including fixes in details. Often in the extras was for archival purposes to retain the original version by @sdausn :)

**Comment by bhagyas** [comment]
Is it possible for you to make those changes in `src/asciidoc/content.adoc`? 

Otherwise, I can have a look at it again and merge those changes.
